In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import hamming

In [41]:
u_data = pd.read_csv('u.data', sep='\t', header=None, 
                     names=['user id','movie id', 'rating','timestamp'], 
                     encoding='iso-8859-1')

item_columns = ['movie id','movie title','release date','video release date','IMDb URL', 'unknown', 'Action', 
                'Adventure', 'Animation',"Children's",'Comedy', 'Crime', 'Documentary','Drama' ,'Fantasy',
                'Film-Noir' , 'Horror' ,'Musical' , 'Mystery' , 'Romance' ,'Sci-Fi', 'Thriller' ,'War' , 'Western']

u_item = pd.read_csv('u.item', sep='|', header=None, 
                     names=item_columns, 
                     encoding='iso-8859-1')

In [42]:
df = pd.merge(left=u_data, right=u_item, how='left', on=['movie id'])

In [43]:
df = df.sort_values('user id').reset_index().drop(columns=['index'])

In [44]:
df.to_csv('cleaned_movielens.csv')

In [45]:
df.columns

Index(['user id', 'movie id', 'rating', 'timestamp', 'movie title',
       'release date', 'video release date', 'IMDb URL', 'unknown', 'Action',
       'Adventure', 'Animation', 'Children's', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='object')

In [46]:
df = df[['user id', 'movie id', 'rating','movie title']]

In [47]:
df.head(5)

   user id  movie id  rating               movie title
0        1        55       5  Professional, The (1994)
1        1       203       4         Unforgiven (1992)
2        1       183       5              Alien (1979)
3        1       150       5           Swingers (1996)
4        1        68       4          Crow, The (1994)

In [48]:
def Favorite_Movie(userId,N):
    userRatings = df[df["user id"] == userId]
    SortedRating = pd.DataFrame.sort_values(userRatings,['rating'],ascending=[0])[:N]
    return SortedRating

In [49]:
Favorite_Movie(10, 5)

      user id  movie id  rating                   movie title
1282       10       133       5     Gone with the Wind (1939)
1414       10       602       5  American in Paris, An (1951)
1350       10       603       5            Rear Window (1954)
1406       10        50       5              Star Wars (1977)
1409       10       611       5                  Laura (1944)

In [50]:
user_per_movie = df['movie id'].value_counts()
movie_per_user = df['user id'].value_counts()

In [51]:
df = df[df["movie id"].isin(user_per_movie[user_per_movie > 100].index)] # movies on the okay-to-recommend list

In [52]:
df = df[df['user id'].isin(movie_per_user[movie_per_user > 50].index)] # real users

In [53]:
User_Movie_Rating_Matrix = pd.pivot_table(df, values='rating', index=['user id'], columns=['movie id'])

In [54]:
User_Movie_Rating_Matrix

movie id,1,2,4,7,8,9,11,12,13,14,...,815,845,866,879,895,926,928,1016,1028,1047
user id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,3.0,4.0,1.0,5.0,2.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4.0,NaN,NaN,2.0,4.0,4.0,NaN,4.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,5.0,5.0,5.0,5.0,3.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,3.0,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4.0,NaN,4.0,4.0,NaN,4.0,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,4.0,5.0,2.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3.0,3.0,5.0,2.0,4.0,3.0,1.0,5.0,5.0,4.0,...,4.0,3.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,5.0,NaN,4.0,NaN,5.0,4.0,3.0,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1.0,NaN,NaN,1.0,NaN,4.0,NaN,NaN,1.0,4.0,...,1.0,2.0,4.0,3.0,NaN,1.0,1.0,NaN,NaN,NaN
16,5.0,NaN,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,5.0,NaN,3.0,NaN,5.0,5.0,NaN,5.0,5.0,5.0,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,5.0,NaN,NaN,5.0,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
22,NaN,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
23,5.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,4.0,5.0,5.0,5.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,5.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,3.0,NaN,NaN,3.0,NaN,4.0,NaN,NaN,3.0,3.0,...,2.0,3.0,NaN,NaN,NaN,2.0,NaN,3.0,NaN,NaN
28,NaN,NaN,NaN,5.0,NaN,NaN,4.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN
41,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,5.0,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,5.0,4.0,NaN,NaN,3.0,NaN,NaN,4.0,4.0
43,5.0,NaN,4.0,4.0,4.0,4.0,5.0,5.0,NaN,2.0,...,4.0,5.0,4.0,4.0,NaN,2.0,NaN,NaN,NaN,3.0
44,4.0,NaN,NaN,5.0,NaN,5.0,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2.0,1.0,2.0,4.0,3.0,NaN,3.0,4.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,4.0,NaN,NaN,4.0,NaN,4.0,NaN,5.0,4.0,4.0,...,NaN,3.0,NaN,4.0,NaN,NaN,NaN,3.0,NaN,NaN
896,4.0,3.0,3.0,4.0,5.0,4.0,2.0,3.0,NaN,NaN,...,NaN,3.0,NaN,NaN,2.0,NaN,3.0,NaN,2.0,NaN
897,5.0,NaN,NaN,NaN,3.0,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,4.0,5.0,NaN,4.0,NaN
899,3.0,3.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
901,5.0,NaN,NaN,NaN,3.0,NaN,NaN,5.0,1.0,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
903,3.0,NaN,4.0,2.0,NaN,3.0,2.0,5.0,5.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
907,5.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0
908,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
910,4.0,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,2.0,NaN,4.0,5.0,2.0,5.0,4.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
916,4.0,3.0,4.0,4.0,NaN,5.0,4.0,4.0,NaN,5.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
918,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
919,4.0,NaN,1.0,3.0,NaN,5.0,4.0,3.0,NaN,4.0,...,2.0,NaN,NaN,3.0,4.0,NaN,NaN,NaN,NaN,3.0
921,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,...,5.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0,4.0,1.0
922,5.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
923,3.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,4.0,NaN,4.0,NaN,NaN,4.0,4.0,NaN,4.0,NaN
924,5.0,3.0,NaN,4.0,NaN,4.0,NaN,4.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
927,5.0,NaN,NaN,3.0,4.0,NaN,5.0,NaN,NaN,NaN,...,3.0,NaN,4.0,NaN,NaN,NaN,4.0,5.0,NaN,4.0
930,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,4.0,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
932,4.0,NaN,NaN,4.0,NaN,5.0,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
933,3.0,NaN,3.0,4.0,NaN,3.0,4.0,4.0,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN
934,2.0,4.0,5.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936,4.0,NaN,NaN,4.0,NaN,4.0,NaN,NaN,4.0,4.0,...,3.0,4.0,2.0,NaN,NaN,4.0,3.0,3.0,NaN,NaN
938,4.0,NaN,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,...,3.0,1.0,5.0,NaN,NaN,3.0,5.0,3.0,5.0,3.0
940,NaN,NaN,2.0,4.0,5.0,3.0,NaN,4.0,NaN,3.0,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN
943,NaN,5.0,NaN,NaN,NaN,3.0,4.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,2.0,2.0

In [55]:
def distance(user_1, user_2):
    try:
        user1_Ratings = User_Movie_Rating_Matrix.transpose()[user_1]
        user2_Ratings = User_Movie_Rating_Matrix.transpose()[user_2]
        distance = hamming(user1_Ratings,user2_Ratings)
    except: 
        distance = np.NaN
    return distance

In [56]:
distance(70, 23)

0.9221556886227545

In [57]:
user = 70
allUsers = pd.DataFrame(User_Movie_Rating_Matrix.index)
allUsers = allUsers[allUsers['user id'] != user]

In [58]:
allUsers["distance"] = allUsers["user id"].apply(lambda x: distance(user,x))

In [59]:
allUsers

     user id  distance
0          1  0.943114
1          2  0.988024
2          3  0.997006
3          5  0.940120
4          6  0.946108
5          7  0.934132
6          8  0.973054
7         10  0.961078
8         11  0.949102
9         12  0.976048
10        13  0.922156
11        14  0.970060
12        15  0.979042
13        16  0.979042
14        18  0.949102
15        21  0.985030
16        22  0.970060
17        23  0.922156
18        24  0.988024
19        25  0.958084
20        26  0.973054
21        28  0.976048
22        37  0.967066
23        38  0.985030
24        41  0.973054
25        42  0.958084
26        43  0.937126
27        44  0.928144
28        48  0.973054
29        49  0.982036
..       ...       ...
533      894  0.967066
534      896  0.907186
535      897  0.961078
536      899  0.937126
537      901  0.958084
538      903  0.973054
539      907  0.979042
540      908  0.979042
541      910  0.973054
542      911  0.958084
543      912  0.979042
544      913  0.940120
545      916  0.889222
546      918  0.988024
547      919  0.958084
548      921  0.964072
549      922  0.958084
550      923  0.994012
551      924  0.970060
552      927  0.970060
553      930  0.991018
554      931  0.988024
555      932  0.949102
556      933  0.958084
557      934  0.943114
558      936  0.982036
559      938  0.979042
560      940  0.964072
561      942  0.985030
562      943  0.964072

[562 rows x 2 columns]

In [60]:
def K_Nearest_Neighbors(user_id, K=10):
    All_Users = pd.DataFrame(User_Movie_Rating_Matrix.index)
    All_Users = All_Users[All_Users['user id'] != user_id]
    All_Users['distance'] = All_Users['user id'].apply(lambda x: distance(user,x))
    KnearestUsers = All_Users.sort_values(["distance"],ascending=True)['user id'][:K]
    return KnearestUsers

In [61]:
KnearestUsers = K_Nearest_Neighbors(70)

In [62]:
NNRatings = User_Movie_Rating_Matrix[User_Movie_Rating_Matrix.index.isin(KnearestUsers)]
NNRatings

movie id,1,2,4,7,8,9,11,12,13,14,...,815,845,866,879,895,926,928,1016,1028,1047
user id,,,,,,,,,,,,,,,,,,,,,
92,4.0,3.0,4.0,4.0,5.0,4.0,4.0,5.0,4.0,NaN,...,NaN,3.0,NaN,NaN,NaN,3.0,3.0,2.0,2.0,1.0
94,4.0,NaN,4.0,4.0,5.0,5.0,5.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,NaN
222,4.0,3.0,3.0,5.0,1.0,5.0,5.0,5.0,NaN,NaN,...,2.0,3.0,NaN,NaN,4.0,NaN,NaN,3.0,NaN,NaN
276,5.0,4.0,4.0,5.0,4.0,5.0,5.0,5.0,NaN,4.0,...,NaN,4.0,NaN,3.0,NaN,NaN,3.0,3.0,3.0,3.0
308,4.0,NaN,5.0,4.0,5.0,4.0,5.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,2.0,3.0
334,NaN,NaN,3.0,5.0,4.0,4.0,4.0,5.0,3.0,3.0,...,3.0,2.0,3.0,3.0,NaN,NaN,NaN,3.0,NaN,NaN
378,4.0,2.0,3.0,4.0,4.0,5.0,3.0,5.0,3.0,5.0,...,NaN,3.0,2.0,NaN,NaN,1.0,2.0,NaN,2.0,2.0
429,3.0,3.0,4.0,2.0,3.0,NaN,4.0,5.0,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,2.0,4.0,3.0,NaN
435,5.0,4.0,4.0,4.0,3.0,4.0,5.0,5.0,NaN,NaN,...,NaN,3.0,NaN,NaN,3.0,3.0,3.0,4.0,2.0,3.0
916,4.0,3.0,4.0,4.0,NaN,5.0,4.0,4.0,NaN,5.0,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df = df.set_index('movie id')

In [65]:
def MovieMeta(movieid):
    title = df.at[movieid,'movie title']
    return title

In [66]:
def topN(user,N=3):
    KnearestUsers = K_Nearest_Neighbors(user)
    NNRatings = User_Movie_Rating_Matrix[User_Movie_Rating_Matrix.index.isin(KnearestUsers)]
    avgRating = NNRatings.apply(np.nanmean).dropna()
    MoviesAlreadyWatched = User_Movie_Rating_Matrix.transpose()[user].dropna().index
    avgRating = avgRating[~avgRating.index.isin(MoviesAlreadyWatched)]
    topNMovies = avgRating.sort_values(ascending=False).index[:N]
    return pd.Series(topNMovies).apply(MovieMeta)

In [68]:
topN(10)

0    [Schindler's List (1993), Schindler's List (19...
1    [Wrong Trousers, The (1993), Wrong Trousers, T...
2    [Edge, The (1997), Edge, The (1997), Edge, The...
Name: movie id, dtype: object